# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hubro Education Technical Blog
email: jorgen@hubro.education
description: > # this means to ignore newlines until "baseurl:"
  Hubro Education's experiences with Meteor, workarounds for issues and
  sharing of experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jorgeer.github.io" # the base hostname & protocol for your site
twitter_username: hubroedu
github_username:  jorgeer

# Build settings
markdown: kramdown
